version: '3'
services:
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
        volumes:
            - ./mongoDbData:/data/db
    mongo-express:
        image: mongo-express
        ports:
            - 8080:8081
        depends_on:
            - 'mongodb'
        restart: unless-stopped
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
            - ME_CONFIG_MONGODB_SERVER=mongodb
    complete-devops-flow-hands-on-project:
        image: rhtsid18dev/complete-devops-flow-hands-on-project:latest
        ports:
            - 3000:3000
